package com.example.enrollment_progress_service.dto.notification;

public enum NotificationType {
    COURSE_SUBMITTED,
    COURSE_APPROVED,
    COURSE_REJECTED,
    COURSE_CONTENT_UPDATED,
    NEW_LESSON_ADDED,
    COURSE_REVIEW_ADDED,
    COURSE_ENROLLED,
    COURSE_COMPLETED,
    CERTIFICATE_GENERATED,
    LIVE_CLASS_REMINDER,
    LIVE_CLASS_STARTED,
    LIVE_CLASS_CANCELLED,
    LIVE_CLASS_RESCHEDULED,
    PAYMENT_SUCCESSFUL,
    PAYMENT_FAILED,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    PAYOUT_PROCESSED,
    KYC_APPROVED,
    KYC_REJECTED,
    WELCOME_EMAIL,
    PASSWORD_RESET,
    LOGIN_ALERT,
    ACCOUNT_SUSPENDED,
    ENROLLMENT_FAILED
}
